# 钉钉配置
dingtalk:
  webhook_url: ${DINGTALK_WEBHOOK}

# 邮箱配置
email:
  sender: ${EMAIL_SENDER}
  receivers: ${EMAIL_RECEIVERS}
  smtp_server: ${SMTP_SERVER}
  smtp_port: ${SMTP_PORT}
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}

# 数据库配置
database:
  host: ${DB_HOST}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  database: ${DB_NAME}
  charset: utf8

# 环境配置
environment:
  allure_path: ${ALLURE_PATH}
  test_url: ${TEST_URL}
  formal_url: ${FORMAL_URL}
  login_url: ${LOGIN_URL}

# 测试配置
test:
  parallel: false
  retry_count: 2
  timeout: 30