database:
  charset: utf8
  database: ${DB_NAME}
  host: ${DB_HOST}
  password: ${DB_PASSWORD}
  user: ${DB_USER}
dingtalk:
  webhook_url: ${DINGTALK_WEBHOOK}
email:
  password: ${EMAIL_PASSWORD}
  receivers: ${EMAIL_RECEIVERS}
  sender: ${EMAIL_SENDER}
  smtp_port: ${SMTP_PORT}
  smtp_server: ${SMTP_SERVER}
  username: ${EMAIL_USERNAME}
environment:
  allure_path: ${ALLURE_PATH}
  current: test
  formal_url: http://192.168.0.143:8282/
  login_url: http://192.168.0.135:8288/account/login
  test_url: http://192.168.0.135:8282/
test:
  parallel: false
  retry_count: 2
  timeout: 30
