name: API自动化测试工作流

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pytest allure-pytest requests numpy

    - name: 安装Allure
      run: |
        sudo apt-add-repository ppa:qameta/allure
        sudo apt-get update
        sudo apt-get install allure

    - name: 修改配置文件路径
      run: |
        # 将Windows路径修改为Linux兼容路径
        sed -i 's/D:\\apiAutomationRH\///g' config.json
        sed -i 's/\\//g' config.json
        # 更新allure路径为Linux环境下的路径
        sed -i 's/D:\\allure-2.33.0\\bin\\allure.bat/allure/g' config.json

    - name: 执行测试
      run: python main_execute.py

    - name: 上传测试报告
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report/